spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 100

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mock_test?rewriteBatchedStatements=true
    username: user
    password: password
    hikari:
      maximum-pool-size: 100
  sql:
    init:
      schema-locations: classpath*:schema.sql
      mode: always
